[package]
name = "knx-rs-demo-client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
knx-rs-core.workspace = true
knx-rs-ip.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
