[package]
name = "knx-rs-demo-device"
version.workspace = true
edition.workspace = true
publish = false

[[bin]]
name = "knx-rs-demo-device"
path = "src/main.rs"

[lib]
name = "knx_rs_demo_device"
path = "src/lib.rs"

[dependencies]
knx-rs-core.workspace = true
knx-rs-ip.workspace = true
knx-rs-device.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
tracing-subscriber.workspace = true
libm.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["full", "test-util"] }
